apiserver:
  image: telemark/tfk-opengov-meetings-api:latest@sha256:d0ffa431e0da920327862380d91653bc6395c8f41bfe1caa6bc7cfec864800cc
  environment:
    OPENGOV_MEETINGS_SERVER_PORT: 8000
    OPENGOV_MEETINGS_DB_CONNECTION: mongodb://dbserver/opengov
  ports:
    - "8000:8000"
  links:
   - dbserver
dbserver:
  image: mongo:3.7.9@sha256:e6f5c2185eb64e0eb4c3d8ef8a903ad0fff0e2554b1bc03c8b1bb25103882102
  environment:
    DB: opengov
    COLLECTION: meetings