apiserver:
  image: telemark/tfk-opengov-meetings-api:latest@sha256:24f5a6e83acff64b1bb0f1cea8fb40e6cdb216672938f1bee99a3c02d801cded
  environment:
    OPENGOV_MEETINGS_SERVER_PORT: 8000
    OPENGOV_MEETINGS_DB_CONNECTION: mongodb://dbserver/opengov
  ports:
    - "8000:8000"
  links:
   - dbserver
dbserver:
  image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
  environment:
    DB: opengov
    COLLECTION: meetings