apiserver:
  image: telemark/tfk-opengov-meetings-api:latest@sha256:f7ee6ae3b64ff1a5d0943282331d840b8bcf510ef0d13a4d9fe3fdbd020e17c5
  environment:
    OPENGOV_MEETINGS_SERVER_PORT: 8000
    OPENGOV_MEETINGS_DB_CONNECTION: mongodb://dbserver/opengov
  ports:
    - "8000:8000"
  links:
   - dbserver
dbserver:
  image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
  environment:
    DB: opengov
    COLLECTION: meetings