apiserver:
  image: telemark/tfk-opengov-meetings-api:latest@sha256:848dbf59c7b6c6b1af0d532c0ffb5fdf6df5783f6b04105110403097c589b16e
  environment:
    OPENGOV_MEETINGS_SERVER_PORT: 8000
    OPENGOV_MEETINGS_DB_CONNECTION: mongodb://dbserver/opengov
  ports:
    - "8000:8000"
  links:
   - dbserver
dbserver:
  image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
  environment:
    DB: opengov
    COLLECTION: meetings